# Hand-curated text-only GenAI canon. (family, tier, title_query, why)
CANON = [
# ---------------- architecture_pretraining_scaling : 40 ----------------
("architecture_pretraining_scaling", 1, "Attention Is All You Need", "The transformer. Every paper below assumes it."),
("architecture_pretraining_scaling", 1, "BERT: Pre-training of Deep Bidirectional", "Encoder pretraining; the fine-tuning era LLMs replaced."),
("architecture_pretraining_scaling", 1, "Language Models are Few-Shot Learners", "GPT-3. In-context learning as a capability, not a trick."),
("architecture_pretraining_scaling", 1, "Exploring the Limits of Transfer Learning", "T5. Text-to-text framing still used for eval and finetuning."),
("architecture_pretraining_scaling", 1, "BART: Denoising Sequence-to-Sequence", "Encoder-decoder denoising; ancestor of modern seq2seq finetuning."),
("architecture_pretraining_scaling", 1, "RoBERTa: A Robustly Optimized", "Showed pretraining recipe beats architecture tinkering."),
("architecture_pretraining_scaling", 1, "Scaling Laws for Neural Language Models", "Loss is predictable from compute. Started the scaling era."),
("architecture_pretraining_scaling", 1, "Training Compute-Optimal Large Language Models", "Chinchilla. Corrected the scaling law; reshaped every training run after."),
("architecture_pretraining_scaling", 1, "Emergent Abilities of Large Language Models", "The claim that capabilities appear discontinuously with scale."),
("architecture_pretraining_scaling", 1, "PaLM: Scaling Language Modeling with Pathways", "540B dense scaling plus the capability report that came with it."),
("architecture_pretraining_scaling", 1, "LLaMA: Open and Efficient Foundation", "The open-weights era starts here."),
("architecture_pretraining_scaling", 1, "Llama 2: Open Foundation and Fine-Tuned Chat", "First open model with a full RLHF pipeline documented."),
("architecture_pretraining_scaling", 1, "The Llama 3 Herd of Models", "Most detailed open frontier-scale training report available."),
("architecture_pretraining_scaling", 1, "GPT-4 Technical Report", "Users ask about GPT-4 by name constantly."),
("architecture_pretraining_scaling", 1, "Mistral 7B", "Proved a small dense model could beat much larger ones. Sliding-window attention."),
("architecture_pretraining_scaling", 1, "Mixtral of Experts", "The MoE model that made sparse models mainstream in open weights."),
("architecture_pretraining_scaling", 1, "Outrageously Large Neural Networks", "Original sparsely-gated MoE layer. Origin of the whole MoE line."),
("architecture_pretraining_scaling", 1, "Switch Transformers", "Simplified MoE routing to top-1; made trillion-param training practical."),
("architecture_pretraining_scaling", 2, "GShard: Scaling Giant Models", "MoE sharding and the parallelism vocabulary still in use."),
("architecture_pretraining_scaling", 1, "DeepSeekMoE: Towards Ultimate Expert", "Fine-grained plus shared experts; the design DeepSeek-V3 is built on."),
("architecture_pretraining_scaling", 1, "DeepSeek-V3 Technical Report", "MLA plus MoE at frontier scale, trained cheaply. Asked about by name."),
("architecture_pretraining_scaling", 1, "Qwen3 Technical Report", "Current open frontier family; hybrid thinking/non-thinking modes."),
("architecture_pretraining_scaling", 2, "Gemini 2.5: Pushing the Frontier", "Named frontier model users ask about; long-context and reasoning claims."),
("architecture_pretraining_scaling", 1, "Mamba: Linear-Time Sequence Modeling", "The credible non-attention alternative. Selective state spaces."),
("architecture_pretraining_scaling", 2, "Transformers are SSMs", "Mamba-2. Unifies attention and SSMs; explains why both work."),
("architecture_pretraining_scaling", 2, "Efficiently Modeling Long Sequences with Structured State Spaces", "S4, the prerequisite Mamba builds on."),
("architecture_pretraining_scaling", 2, "RWKV: Reinventing RNNs", "The other serious linear-time line; RNN inference with transformer training."),
("architecture_pretraining_scaling", 1, "RoFormer: Enhanced Transformer with Rotary", "RoPE. Positional encoding in essentially every modern LLM."),
("architecture_pretraining_scaling", 2, "Train Short, Test Long", "ALiBi. The other position scheme, and the length-extrapolation framing."),
("architecture_pretraining_scaling", 1, "Layer Normalization", "Prerequisite. Pre-LN vs post-LN is still a live training question."),
("architecture_pretraining_scaling", 2, "Root Mean Square Layer Normalization", "RMSNorm. What Llama and nearly every open model actually uses."),
("architecture_pretraining_scaling", 2, "GLU Variants Improve Transformer", "SwiGLU. The FFN every modern LLM uses, from a two-page paper."),
("architecture_pretraining_scaling", 1, "Adam: A Method for Stochastic Optimization", "Prerequisite. AdamW is still the default optimizer."),
("architecture_pretraining_scaling", 1, "Neural Machine Translation of Rare Words", "BPE. Why tokenizers behave the way they do."),
("architecture_pretraining_scaling", 1, "Megatron-LM: Training Multi-Billion", "Tensor parallelism. The vocabulary of distributed training."),
("architecture_pretraining_scaling", 1, "ZeRO: Memory Optimizations", "Sharded optimizer state; what DeepSpeed and FSDP implement."),
("architecture_pretraining_scaling", 1, "GQA: Training Generalized Multi-Query", "Grouped-query attention; the KV-cache/quality tradeoff everyone ships."),
("architecture_pretraining_scaling", 2, "Fast Transformer Decoding", "Multi-query attention, the idea GQA generalizes."),
("architecture_pretraining_scaling", 2, "OPT: Open Pre-trained Transformer", "First honest open replication of GPT-3, logbook included."),
("architecture_pretraining_scaling", 2, "BLOOM: A 176B-Parameter Open-Access", "The open multilingual counterweight; governance precedent."),

# ---------------- post_training_rlhf_dpo : 35 ----------------
("post_training_rlhf_dpo", 1, "Training language models to follow instructions", "InstructGPT. The paper that turned a base model into ChatGPT."),
("post_training_rlhf_dpo", 1, "Deep reinforcement learning from human preferences", "Origin of preference-based RL. RLHF starts here."),
("post_training_rlhf_dpo", 1, "Fine-Tuning Language Models from Human Preferences", "First application of that RL loop to language models."),
("post_training_rlhf_dpo", 1, "Learning to summarize from human feedback", "The bridge paper: reward models on real text, before InstructGPT."),
("post_training_rlhf_dpo", 1, "Proximal Policy Optimization Algorithms", "PPO. The optimizer inside classic RLHF."),
("post_training_rlhf_dpo", 2, "High-Dimensional Continuous Control Using Generalized Advantage", "GAE. The advantage estimator PPO depends on."),
("post_training_rlhf_dpo", 1, "Training a Helpful and Harmless Assistant", "Anthropic HH. Helpfulness/harmlessness tradeoff made measurable."),
("post_training_rlhf_dpo", 1, "Constitutional AI", "RLAIF with a written constitution; replaced human harm labels."),
("post_training_rlhf_dpo", 1, "Direct Preference Optimization", "DPO. Removed the reward model; now the default alignment method."),
("post_training_rlhf_dpo", 1, "Self-Instruct: Aligning Language Models", "Synthetic instruction data. Made open instruction tuning possible."),
("post_training_rlhf_dpo", 1, "Finetuned Language Models Are Zero-Shot Learners", "FLAN. Instruction tuning as a general capability unlock."),
("post_training_rlhf_dpo", 1, "Scaling Instruction-Finetuned Language Models", "FLAN-T5. Scaling behaviour of instruction tuning."),
("post_training_rlhf_dpo", 2, "Multitask Prompted Training Enables Zero-Shot", "T0. Parallel discovery to FLAN, with the public prompt collection."),
("post_training_rlhf_dpo", 2, "Super-NaturalInstructions", "1600+ task instruction benchmark; the data backbone of the era."),
("post_training_rlhf_dpo", 1, "LIMA: Less Is More for Alignment", "1000 examples beat RLHF. The superficial-alignment hypothesis."),
("post_training_rlhf_dpo", 2, "Zephyr: Direct Distillation of LM Alignment", "dDPO recipe; the template most open finetunes copied."),
("post_training_rlhf_dpo", 2, "RLAIF vs. RLHF", "Direct head-to-head of AI vs human feedback at scale."),
("post_training_rlhf_dpo", 1, "Scaling Laws for Reward Model Overoptimization", "Why reward hacking happens and when. Core to debugging any RLHF run."),
("post_training_rlhf_dpo", 1, "Open Problems and Fundamental Limitations of Reinforcement Learning from Human", "The honest catalogue of what RLHF cannot fix."),
("post_training_rlhf_dpo", 1, "DeepSeekMath: Pushing the Limits", "Introduces GRPO, the algorithm behind R1 and most 2025 reasoning RL."),
("post_training_rlhf_dpo", 1, "DAPO: An Open-Source LLM Reinforcement Learning System", "Open, reproducible large-scale RL recipe with the tricks written down."),
("post_training_rlhf_dpo", 2, "Reinforced Self-Training", "ReST. Offline iterative self-improvement loop."),
("post_training_rlhf_dpo", 2, "RRHF: Rank Responses", "Early RL-free alignment via ranking loss."),
("post_training_rlhf_dpo", 2, "SLiC-HF", "Sequence likelihood calibration; the other pre-DPO RL-free line."),
("post_training_rlhf_dpo", 2, "SimPO: Simple Preference Optimization", "Reference-free DPO variant; common in practice."),
("post_training_rlhf_dpo", 2, "ORPO: Monolithic Preference Optimization", "Merges SFT and preference tuning into one stage."),
("post_training_rlhf_dpo", 2, "KTO: Model Alignment as Prospect", "Learns from unpaired good/bad labels; cheapest data requirement."),
("post_training_rlhf_dpo", 2, "Improving alignment of dialogue agents via targeted human judgements", "Sparrow. Rule-conditioned RLHF plus evidence citation."),
("post_training_rlhf_dpo", 1, "Self-Rewarding Language Models", "Model judges its own outputs to improve. The self-improvement loop."),
("post_training_rlhf_dpo", 2, "WizardLM: Empowering Large Language Models to Follow Complex", "Evol-Instruct. How synthetic instruction difficulty is escalated."),
("post_training_rlhf_dpo", 2, "Enhancing Chat Language Models by Scaling High-quality", "UltraChat. Large-scale synthetic dialogue data."),
("post_training_rlhf_dpo", 1, "Tulu 3", "Fully open post-training recipe, data included. Best reproduction target."),
("post_training_rlhf_dpo", 2, "A General Theoretical Paradigm to Understand Learning from Human Preferences", "IPO. Explains the DPO overfitting failure mode."),
("post_training_rlhf_dpo", 2, "Back to Basics: Revisiting REINFORCE", "RLOO. Shows PPO machinery is often unnecessary for LLMs."),
("post_training_rlhf_dpo", 2, "AlpacaFarm", "Simulated preference feedback; made alignment research cheap."),

# ---------------- reasoning_test_time_compute : 35 ----------------
("reasoning_test_time_compute", 1, "Chain-of-Thought Prompting Elicits Reasoning", "The paper that made reasoning a prompting property."),
("reasoning_test_time_compute", 1, "Large Language Models are Zero-Shot Reasoners", "Let us think step by step. Zero-shot CoT."),
("reasoning_test_time_compute", 1, "Self-Consistency Improves Chain of Thought", "Sampling plus majority vote. First real test-time compute scaling."),
("reasoning_test_time_compute", 2, "Least-to-Most Prompting", "Decomposition prompting; ancestor of planner-style agents."),
("reasoning_test_time_compute", 1, "Tree of Thoughts", "Search over reasoning states instead of a single chain."),
("reasoning_test_time_compute", 2, "Show Your Work: Scratchpads", "Pre-CoT demonstration that intermediate tokens carry computation."),
("reasoning_test_time_compute", 1, "STaR: Bootstrapping Reasoning", "Train on your own correct rationales. Seed of all self-training reasoning."),
("reasoning_test_time_compute", 1, "Training Verifiers to Solve Math Word Problems", "GSM8K plus verifiers. Verification as a separate capability."),
("reasoning_test_time_compute", 1, "Solving math word problems with process- and outcome-based feedback", "Process vs outcome supervision, stated cleanly."),
("reasoning_test_time_compute", 1, "Verify Step by Step", "Process reward models beat outcome models. Basis of modern PRMs."),
("reasoning_test_time_compute", 2, "PAL: Program-aided Language Models", "Offload computation to an interpreter instead of the model."),
("reasoning_test_time_compute", 2, "Program of Thoughts Prompting", "The parallel formulation of the same idea; cited alongside PAL."),
("reasoning_test_time_compute", 2, "Solving Quantitative Reasoning Problems with Language Models", "Minerva. Showed math ability comes from data, not tricks."),
("reasoning_test_time_compute", 1, "Self-Refine", "Iterative self-critique and revision, no extra training."),
("reasoning_test_time_compute", 1, "Large Language Models Cannot Self-Correct Reasoning Yet", "The rebuttal. Necessary counterweight to Self-Refine."),
("reasoning_test_time_compute", 1, "DeepSeek-R1", "Pure RL produces reasoning behaviour. The biggest result of 2025."),
("reasoning_test_time_compute", 1, "s1: Simple test-time scaling", "1k examples plus budget forcing. Shows how cheap reasoning can be."),
("reasoning_test_time_compute", 1, "Scaling LLM Test-Time Compute", "The scaling-law treatment of inference compute vs parameters."),
("reasoning_test_time_compute", 1, "Large Language Monkeys", "Repeated sampling scales coverage predictably. Why pass@k matters."),
("reasoning_test_time_compute", 2, "Chain of Thought Empowers Transformers", "Theory: why intermediate tokens add expressive power."),
("reasoning_test_time_compute", 1, "Understanding R1-Zero-Like Training", "Critical audit of R1-style RL; catches the evaluation artifacts."),
("reasoning_test_time_compute", 1, "Does Reinforcement Learning Really Incentivize Reasoning", "Argues RL sharpens rather than creates ability. Key open dispute."),
("reasoning_test_time_compute", 2, "Do NOT Think That Much", "Overthinking in o1-style models; the cost side of reasoning."),
("reasoning_test_time_compute", 2, "Training Large Language Models to Reason in a Continuous Latent Space", "Coconut. Reasoning without emitting tokens."),
("reasoning_test_time_compute", 2, "ReST-MCTS", "Tree search plus process rewards for self-training."),
("reasoning_test_time_compute", 2, "Search-o1", "Agentic retrieval inside a reasoning model chain."),
("reasoning_test_time_compute", 1, "Search-R1", "RL-trained search-and-reason. Directly relevant to agentic RAG."),
("reasoning_test_time_compute", 2, "Challenging BIG-Bench Tasks", "BBH. The benchmark CoT claims are actually measured on."),
("reasoning_test_time_compute", 2, "Measuring and Narrowing the Compositionality Gap", "Self-Ask. Why multi-hop fails and how decomposition helps."),
("reasoning_test_time_compute", 2, "MAmmoTH: Building Math Generalist", "Hybrid CoT/PoT instruction tuning for math generalists."),
("reasoning_test_time_compute", 2, "Quiet-STaR", "Learning to think before every token, not just on math."),
("reasoning_test_time_compute", 2, "rStar-Math", "Small models matching large ones via deep search. Practical for local use."),
("reasoning_test_time_compute", 1, "Language Models Don't Always Say What They Think", "CoT can be unfaithful. Critical caveat for anything citing reasoning traces."),
("reasoning_test_time_compute", 2, "Measuring Faithfulness in Chain-of-Thought Reasoning", "Makes that unfaithfulness measurable."),
("reasoning_test_time_compute", 2, "Chain-of-Thought Reasoning Without Prompting", "CoT paths exist in decoding; changes how we think prompting works."),

# ---------------- rag_retrieval : 35 ----------------
("rag_retrieval", 1, "Retrieval-Augmented Generation for Knowledge-Intensive", "The RAG paper. Names the pattern this whole product implements."),
("rag_retrieval", 1, "Dense Passage Retrieval for Open-Domain Question Answering", "DPR. Dense retrieval replaces BM25; the bi-encoder recipe."),
("rag_retrieval", 1, "REALM: Retrieval-Augmented Language Model Pre-Training", "Retrieval trained end-to-end with the LM. Predates RAG."),
("rag_retrieval", 1, "Leveraging Passage Retrieval with Generative Models", "FiD. Fusion-in-decoder, still the strongest simple reader design."),
("rag_retrieval", 2, "Improving language models by retrieving from trillions of tokens", "RETRO. Retrieval baked into pretraining instead of inference."),
("rag_retrieval", 2, "Atlas: Few-shot Learning with Retrieval Augmented", "Few-shot retrieval-augmented LM; joint retriever/reader training."),
("rag_retrieval", 2, "Generalization through Memorization", "kNN-LM. Non-parametric memory at the token level."),
("rag_retrieval", 1, "Unsupervised Dense Information Retrieval with Contrastive Learning", "Contriever. Unsupervised dense retrieval; the common embedding baseline."),
("rag_retrieval", 2, "Approximate Nearest Neighbor Negative Contrastive Learning", "ANCE. Hard negative mining, the thing that actually makes dense retrieval work."),
("rag_retrieval", 1, "BEIR: A Heterogenous Benchmark", "The zero-shot retrieval benchmark. How you know your retriever generalizes."),
("rag_retrieval", 1, "MS MARCO", "The dataset nearly every retriever and reranker is trained on."),
("rag_retrieval", 1, "Sentence-BERT", "Sentence embeddings via siamese networks. Origin of the embedding stack."),
("rag_retrieval", 1, "Text Embeddings by Weakly-Supervised Contrastive Pre-training", "E5. The modern embedding training recipe."),
("rag_retrieval", 2, "Qwen3 Embedding", "Current open embedding and reranking family; direct production option."),
("rag_retrieval", 1, "ColBERT: Efficient and Effective Passage Search", "Late interaction. The third retrieval paradigm beyond sparse and dense."),
("rag_retrieval", 2, "ColBERTv2", "Makes late interaction storage-practical. What people actually deploy."),
("rag_retrieval", 1, "Precise Zero-Shot Dense Retrieval without Relevance Labels", "HyDE. Query expansion by hallucinating an answer first."),
("rag_retrieval", 1, "Self-RAG", "Model decides when to retrieve and critiques what it retrieved."),
("rag_retrieval", 2, "Corrective Retrieval Augmented Generation", "CRAG. What to do when retrieval returns garbage."),
("rag_retrieval", 1, "RAPTOR", "Hierarchical summary tree indexing. The main answer to chunking loss."),
("rag_retrieval", 1, "From Local to Global: A Graph RAG Approach", "GraphRAG. Handles global questions a chunk retriever cannot."),
("rag_retrieval", 1, "Interleaving Retrieval with Chain-of-Thought Reasoning", "IRCoT. Multi-hop retrieval interleaved with reasoning."),
("rag_retrieval", 2, "Adaptive-RAG", "Route by query complexity instead of always retrieving."),
("rag_retrieval", 1, "When Not to Trust Language Models", "When retrieval helps vs hurts, by entity popularity. Directly actionable."),
("rag_retrieval", 1, "Lost in the Middle", "Position bias in long contexts. Why reranking and ordering matter."),
("rag_retrieval", 2, "Retrieval Augmented Generation or Long-Context LLMs", "The RAG-vs-long-context question, measured rather than argued."),
("rag_retrieval", 2, "Retrieval Augmentation Reduces Hallucination in Conversation", "Early evidence for the core claim of the whole field."),
("rag_retrieval", 2, "KILT", "Unified knowledge-intensive benchmark with shared provenance."),
("rag_retrieval", 1, "RAGAS", "Reference-free RAG evaluation. The eval vocabulary this repo uses."),
("rag_retrieval", 2, "Benchmarking Large Language Models in Retrieval-Augmented Generation", "RGB. Isolates noise, rejection, and counterfactual robustness."),
("rag_retrieval", 2, "Dense X Retrieval", "Propositions as retrieval units. The cleanest chunk-granularity study."),
("rag_retrieval", 1, "Retrieval-Augmented Generation for Large Language Models: A Survey", "One chunk that maps the entire field. High leverage in a 300-paper corpus."),
("rag_retrieval", 2, "Billion-scale similarity search with GPUs", "FAISS. The index underneath most vector stores."),
("rag_retrieval", 1, "Active Retrieval Augmented Generation", "FLARE. Retrieve mid-generation, when the model shows it is unsure."),
("rag_retrieval", 2, "Is ChatGPT Good at Search", "RankGPT. LLM listwise reranking, the pattern this repo uses Cohere for."),

# ---------------- agents_tools_multiagent : 25 ----------------
("agents_tools_multiagent", 1, "ReAct: Synergizing Reasoning and Acting", "The reason-act-observe loop every agent framework implements."),
("agents_tools_multiagent", 1, "Toolformer", "Models learn when to call tools by self-supervision. Origin of tool use."),
("agents_tools_multiagent", 1, "Reflexion", "Verbal self-reflection stored in memory across attempts."),
("agents_tools_multiagent", 1, "Generative Agents", "Memory, reflection, and planning architecture. Most-copied agent design."),
("agents_tools_multiagent", 1, "AutoGen", "Multi-agent conversation as a programming model."),
("agents_tools_multiagent", 2, "Voyager", "Open-ended skill library that grows. The lifelong-learning agent."),
("agents_tools_multiagent", 2, "HuggingGPT", "LLM as controller routing to specialist models."),
("agents_tools_multiagent", 1, "WebGPT", "Browser-assisted QA with human feedback. The first real research agent."),
("agents_tools_multiagent", 2, "WebShop", "First scalable grounded web-interaction benchmark."),
("agents_tools_multiagent", 1, "WebArena", "Realistic, reproducible web agent environment. The honest difficulty check."),
("agents_tools_multiagent", 1, "SWE-agent", "Agent-computer interface design. Why tool ergonomics decide agent success."),
("agents_tools_multiagent", 2, "MetaGPT", "SOP-driven role assignment in multi-agent systems."),
("agents_tools_multiagent", 2, "CAMEL: Communicative Agents", "Role-playing agent communication; early multi-agent scaffold."),
("agents_tools_multiagent", 1, "ToolLLM", "Tool use at 16k+ real APIs. The scale test for function calling."),
("agents_tools_multiagent", 2, "Gorilla", "API-calling LLM with retrieval over docs; reduces hallucinated calls."),
("agents_tools_multiagent", 1, "AgentBench", "Multi-environment agent evaluation. How agent claims get checked."),
("agents_tools_multiagent", 2, "tau-bench", "Tool-agent-user interaction with rules. Realistic reliability measurement."),
("agents_tools_multiagent", 2, "BrowseComp", "Hard browsing benchmark for search agents."),
("agents_tools_multiagent", 1, "A survey of agent interoperability protocols", "MCP, A2A and friends in one place. Users ask about MCP constantly."),
("agents_tools_multiagent", 1, "MemGPT", "OS-style paged memory for agents. The long-term memory pattern."),
("agents_tools_multiagent", 2, "Mem0", "Production agent memory; the current practical implementation."),
("agents_tools_multiagent", 2, "Cognitive Architectures for Language Agents", "CoALA. The framework that organizes the whole agent literature."),
("agents_tools_multiagent", 2, "Executable Code Actions Elicit Better LLM Agents", "CodeAct. Code as the action space instead of JSON."),
("agents_tools_multiagent", 2, "The Rise and Potential of Large Language Model Based Agents", "Survey. One chunk covering the agent landscape."),
("agents_tools_multiagent", 2, "Chain of Agents", "Multi-agent collaboration for long-context tasks."),

# ---------------- efficient_inference_serving : 22 ----------------
("efficient_inference_serving", 1, "FlashAttention", "IO-aware exact attention. The single biggest practical speedup."),
("efficient_inference_serving", 1, "FlashAttention-2", "The version actually deployed everywhere."),
("efficient_inference_serving", 2, "FlashAttention-3", "Hopper-era rewrite; current state of the art kernel."),
("efficient_inference_serving", 1, "Efficient Memory Management for Large Language Model Serving", "vLLM and PagedAttention. The serving system most people run."),
("efficient_inference_serving", 1, "Fast Inference from Transformers via Speculative Decoding", "Speculative decoding. Free latency from a draft model."),
("efficient_inference_serving", 2, "Accelerating Large Language Model Decoding with Speculative Sampling", "The parallel DeepMind formulation; both are cited together."),
("efficient_inference_serving", 2, "Medusa", "Multiple decoding heads instead of a draft model. Simpler to deploy."),
("efficient_inference_serving", 1, "GPTQ", "Post-training 4-bit quantization. Why 70B runs on one GPU."),
("efficient_inference_serving", 1, "AWQ", "Activation-aware quantization; the other half of the local-LLM stack."),
("efficient_inference_serving", 1, "LLM.int8()", "Outlier features and why naive 8-bit quantization breaks."),
("efficient_inference_serving", 2, "SmoothQuant", "Migrates activation outliers to weights. W8A8 that actually works."),
("efficient_inference_serving", 2, "SparseGPT", "One-shot pruning at scale. The pruning counterpart to quantization."),
("efficient_inference_serving", 1, "Distilling the Knowledge in a Neural Network", "Prerequisite. Every distilled small model traces here."),
("efficient_inference_serving", 2, "DistilBERT", "The distillation result that made the technique standard practice."),
("efficient_inference_serving", 1, "Efficiently Scaling Transformer Inference", "The analytical model of inference cost: memory vs compute bound."),
("efficient_inference_serving", 2, "FlexGen", "High-throughput inference on one GPU via offloading."),
("efficient_inference_serving", 1, "The Curious Case of Neural Text Degeneration", "Nucleus sampling. Why top-p exists and what temperature does."),
("efficient_inference_serving", 2, "Transformers are RNNs", "Linear attention. The O(n) attention framing."),
("efficient_inference_serving", 2, "Rethinking Attention with Performers", "The other major linear-attention approximation."),
("efficient_inference_serving", 1, "SGLang", "RadixAttention and structured generation. Current serving alternative to vLLM."),
("efficient_inference_serving", 2, "H2O: Heavy-Hitter Oracle", "KV cache eviction. How long-context serving stays affordable."),
("efficient_inference_serving", 2, "Efficient Streaming Language Models with Attention Sinks", "StreamingLLM. Attention sinks and infinite-length streaming."),

# ---------------- evaluation_benchmarks : 20 ----------------
("evaluation_benchmarks", 1, "Measuring Massive Multitask Language Understanding", "MMLU. The benchmark every model report leads with."),
("evaluation_benchmarks", 1, "Evaluating Large Language Models Trained on Code", "HumanEval and Codex. The code benchmark everyone quotes."),
("evaluation_benchmarks", 1, "HellaSwag", "Commonsense NLI; the standard base-model sanity check."),
("evaluation_benchmarks", 2, "GLUE: A Multi-Task Benchmark", "Prerequisite. Where LLM benchmarking culture came from."),
("evaluation_benchmarks", 2, "SuperGLUE", "The harder successor; shows the saturate-and-replace cycle."),
("evaluation_benchmarks", 2, "Beyond the Imitation Game", "BIG-bench. 200+ tasks probing where scaling does not help."),
("evaluation_benchmarks", 1, "TruthfulQA", "Measures imitative falsehoods. The hallucination benchmark."),
("evaluation_benchmarks", 1, "GPQA", "Google-proof graduate questions. The current hard knowledge benchmark."),
("evaluation_benchmarks", 1, "MMLU-Pro", "Fixes MMLU saturation and noise. The replacement people cite now."),
("evaluation_benchmarks", 1, "Judging LLM-as-a-Judge with MT-Bench", "LLM-as-judge validated against humans. Underpins most modern eval."),
("evaluation_benchmarks", 1, "Chatbot Arena", "Human pairwise preference at scale. The ranking people actually trust."),
("evaluation_benchmarks", 2, "Length-Controlled AlpacaEval", "Debiasing automatic judges for verbosity. A real, common failure."),
("evaluation_benchmarks", 2, "Prometheus 2", "Open evaluator model; the alternative to GPT-4 as judge."),
("evaluation_benchmarks", 1, "Large Language Models are not Fair Evaluators", "Position bias in LLM judges. Required caveat before trusting any of it."),
("evaluation_benchmarks", 1, "Holistic Evaluation of Language Models", "HELM. Multi-metric evaluation instead of one leaderboard number."),
("evaluation_benchmarks", 1, "Measuring Mathematical Problem Solving With the MATH Dataset", "MATH. The competition-math benchmark reasoning work reports on."),
("evaluation_benchmarks", 2, "Know What You Don't Know", "SQuAD 2.0. Unanswerable questions -- the abstention behaviour RAG needs."),
("evaluation_benchmarks", 2, "HotpotQA", "Multi-hop QA with supporting facts. The multi-hop RAG testbed."),
("evaluation_benchmarks", 2, "BERTScore", "Embedding-based generation metric; the bridge past BLEU/ROUGE."),
("evaluation_benchmarks", 1, "Survey of Hallucination in Natural Language Generation", "Defines and taxonomizes hallucination. Grounds every groundedness eval."),

# ---------------- safety_alignment_redteam : 20 ----------------
("safety_alignment_redteam", 1, "Universal and Transferable Adversarial Attacks on Aligned", "GCG. Automated transferable jailbreaks; broke the safety-training assumption."),
("safety_alignment_redteam", 1, "Ignore Previous Prompt", "Prompt injection, named and demonstrated."),
("safety_alignment_redteam", 1, "Not what you've signed up for", "Indirect prompt injection via retrieved content. The RAG-specific threat."),
("safety_alignment_redteam", 1, "Jailbroken: How Does LLM Safety Training Fail", "The two failure modes: competing objectives and mismatched generalization."),
("safety_alignment_redteam", 2, "Red Teaming Language Models with Language Models", "Automated red teaming. Scales adversarial testing."),
("safety_alignment_redteam", 2, "Red Teaming Language Models to Reduce Harms", "The empirical scaling behaviour of human red teaming."),
("safety_alignment_redteam", 1, "RealToxicityPrompts", "Toxic degeneration benchmark; the original safety eval."),
("safety_alignment_redteam", 1, "Extracting Training Data from Large Language Models", "Memorization and privacy leakage, demonstrated."),
("safety_alignment_redteam", 2, "Concrete Problems in AI Safety", "Prerequisite. The vocabulary for reward hacking and side effects."),
("safety_alignment_redteam", 2, "Ethical and social risks of harm from Language Models", "The risk taxonomy most policy work builds on."),
("safety_alignment_redteam", 1, "Sleeper Agents", "Backdoors that survive safety training. The strongest deceptive-alignment result."),
("safety_alignment_redteam", 1, "Alignment faking in large language models", "Models strategically comply during training. Directly relevant to evals."),
("safety_alignment_redteam", 2, "StruQ", "Structured queries as a prompt-injection defence."),
("safety_alignment_redteam", 1, "Language Models (Mostly) Know What They Know", "Calibration and self-knowledge. The basis for abstention behaviour."),
("safety_alignment_redteam", 1, "Weak-to-Strong Generalization", "Can weak supervisors align strong models. The scalable-oversight experiment."),
("safety_alignment_redteam", 2, "Improving Alignment and Robustness with Circuit Breakers", "Representation-level defence instead of refusal training."),
("safety_alignment_redteam", 2, "Llama Guard", "Deployable input/output safety classifier. The practical guardrail."),
("safety_alignment_redteam", 1, "HarmBench", "Standardized red-teaming evaluation. Makes jailbreak claims comparable."),
("safety_alignment_redteam", 2, "Safe RLHF", "Separates helpfulness and harmlessness into a constrained objective."),
("safety_alignment_redteam", 1, "On the Opportunities and Risks of Foundation Models", "The framing document for the whole field. One chunk, huge coverage."),

# ---------------- long_context : 15 ----------------
("long_context", 1, "Longformer", "Sliding-window plus global attention. The first practical long-doc transformer."),
("long_context", 2, "Big Bird", "Sparse attention with theoretical guarantees; the parallel line to Longformer."),
("long_context", 1, "Transformer-XL", "Segment recurrence and relative positions. Prerequisite for everything after."),
("long_context", 2, "Generating Long Sequences with Sparse Transformers", "Factorized sparse attention; the original sparse-attention paper."),
("long_context", 2, "Reformer", "LSH attention and reversible layers. The memory-efficiency angle."),
("long_context", 1, "YaRN", "The context-extension method people actually use on open models."),
("long_context", 1, "Extending Context Window of Large Language Models via Positional Interpolation", "Position interpolation. The simple trick that started context extension."),
("long_context", 2, "Effective Long-Context Scaling of Foundation Models", "Llama-scale continued pretraining for long context, with ablations."),
("long_context", 2, "Ring Attention", "Context length scales with device count. How million-token training happens."),
("long_context", 2, "Leave No Context Behind", "Infini-attention. Compressive memory for unbounded context."),
("long_context", 1, "RULER", "Real long-context evaluation beyond needle-in-a-haystack. Exposes fake claims."),
("long_context", 2, "LongBench", "Bilingual multitask long-context benchmark."),
("long_context", 2, "LongRoPE", "Extends to 2M tokens; the aggressive end of RoPE scaling."),
("long_context", 2, "Titans: Learning to Memorize at Test Time", "Learned memory module at inference. The current research direction."),
("long_context", 2, "Compressive Transformers", "Compressed long-range memory; the idea Infini-attention revives."),

# ---------------- peft_adaptation : 14 ----------------
("peft_adaptation", 1, "LoRA: Low-Rank Adaptation", "The default finetuning method. Nothing in PEFT is more used."),
("peft_adaptation", 1, "QLoRA", "4-bit base plus LoRA. Why finetuning a 70B on one GPU is possible."),
("peft_adaptation", 1, "Parameter-Efficient Transfer Learning for NLP", "Adapters. The original PEFT idea LoRA improved on."),
("peft_adaptation", 1, "Prefix-Tuning", "Continuous prompts in every layer; the other PEFT family."),
("peft_adaptation", 1, "The Power of Scale for Parameter-Efficient Prompt Tuning", "Prompt tuning closes the gap with scale. The cleanest PEFT scaling result."),
("peft_adaptation", 2, "BitFit", "Tune only biases. The extreme baseline that keeps PEFT honest."),
("peft_adaptation", 1, "Towards a Unified View of Parameter-Efficient Transfer Learning", "Shows adapters, prefix tuning and LoRA are one design space."),
("peft_adaptation", 2, "Few-Shot Parameter-Efficient Fine-Tuning is Better and Cheaper", "IA3. PEFT beats in-context learning on cost and quality."),
("peft_adaptation", 2, "DoRA", "Weight-decomposed LoRA; the common accuracy upgrade."),
("peft_adaptation", 1, "Editing Models with Task Arithmetic", "Add and subtract skills as weight vectors. The basis of model merging."),
("peft_adaptation", 2, "Model soups", "Averaging finetuned weights beats picking the best. Merging, empirically."),
("peft_adaptation", 2, "TIES-Merging", "Resolves interference when merging many finetunes."),
("peft_adaptation", 1, "LoRA Learns Less and Forgets Less", "The honest LoRA-vs-full-finetuning tradeoff study."),
("peft_adaptation", 2, "LlamaFactory", "The unified finetuning toolkit most practitioners actually run."),

# ---------------- data_curation_synthetic : 14 ----------------
("data_curation_synthetic", 1, "The Pile", "The first big open pretraining corpus. Started open data curation."),
("data_curation_synthetic", 1, "The RefinedWeb Dataset for Falcon LLM", "Web-only data, properly filtered, beats curated corpora."),
("data_curation_synthetic", 1, "The FineWeb Datasets", "Current open web-data standard, with every ablation published."),
("data_curation_synthetic", 2, "Dolma", "Fully open 3T corpus plus the toolkit. Reproducible pretraining data."),
("data_curation_synthetic", 1, "Textbooks Are All You Need", "phi-1. Data quality beats data quantity, demonstrated."),
("data_curation_synthetic", 2, "Textbooks Are All You Need II", "phi-1.5. Confirms the result generalizes past code."),
("data_curation_synthetic", 1, "Deduplicating Training Data Makes Language Models Better", "Dedup changes memorization and eval validity. Cheap and essential."),
("data_curation_synthetic", 1, "Scaling Data-Constrained Language Models", "What happens when you run out of tokens. Repetition scaling laws."),
("data_curation_synthetic", 2, "DataComp-LM", "Data curation as a controlled benchmark instead of folklore."),
("data_curation_synthetic", 2, "Rephrasing the Web", "Synthetic rewriting of web text; cheap quality gains."),
("data_curation_synthetic", 1, "The Curse of Recursion", "Model collapse from training on generated data. The limit of synthetic data."),
("data_curation_synthetic", 1, "A Careful Examination of Large Language Model Performance on Grade School", "GSM1k. Benchmark contamination measured, not speculated."),
("data_curation_synthetic", 2, "WildChat", "Real user-ChatGPT traffic. Shows what people actually ask."),
("data_curation_synthetic", 2, "Data Selection for Language Models via Importance Resampling", "DSIR. Principled data selection rather than heuristics."),

# ---------------- interpretability_internals : 12 ----------------
("interpretability_internals", 1, "Scaling and evaluating sparse autoencoders", "Superposition and SAE feature extraction at frontier scale."),
("interpretability_internals", 1, "An Explanation of In-context Learning as Implicit Bayesian", "Why in-context learning works at all. The main mechanistic account."),
("interpretability_internals", 1, "Locating and Editing Factual Associations in GPT", "ROME. Facts live in MLP layers and can be edited."),
("interpretability_internals", 1, "Transformer Feed-Forward Layers Are Key-Value Memories", "The result ROME depends on. What FFNs actually store."),
("interpretability_internals", 1, "Interpretability in the Wild", "The IOI circuit. A full mechanism traced end to end in GPT-2."),
("interpretability_internals", 1, "Sparse Autoencoders Find Highly Interpretable Features", "SAEs. The main tool for extracting monosemantic features."),
("interpretability_internals", 2, "Representation Engineering", "Top-down control via activation steering. Practical, not just descriptive."),
("interpretability_internals", 2, "Axiomatic Attribution for Deep Networks", "Integrated gradients. Prerequisite attribution method."),
("interpretability_internals", 2, "Language Models as Knowledge Bases", "LAMA. Started the probing-for-knowledge line."),
("interpretability_internals", 1, "Rethinking the Role of Demonstrations", "In-context learning does not need correct labels. Reframed prompting."),
("interpretability_internals", 1, "Pythia: A Suite for Analyzing Large Language Models", "Checkpoints across scale and time. The substrate for training-dynamics work."),
("interpretability_internals", 1, "Are Emergent Abilities of Large Language Models a Mirage", "Argues emergence is a metric artifact. The essential counterpoint."),

# ---------------- code_software_engineering : 8 ----------------
("code_software_engineering", 1, "SWE-bench", "Real GitHub issues. The benchmark that redefined coding agents."),
("code_software_engineering", 1, "Code Llama", "The open code model family and its long-context/infilling recipe."),
("code_software_engineering", 1, "StarCoder", "Fully open code LLM with governed, licence-clean data."),
("code_software_engineering", 2, "CodeGen", "Multi-turn program synthesis; the conversational coding formulation."),
("code_software_engineering", 2, "Competition-Level Code Generation with AlphaCode", "Sampling plus filtering at massive scale for competitive programming."),
("code_software_engineering", 1, "Program Synthesis with Large Language Models", "MBPP. The other benchmark quoted next to HumanEval."),
("code_software_engineering", 2, "CodeT5", "Identifier-aware encoder-decoder; the pre-LLM code model baseline."),
("code_software_engineering", 2, "BigCodeBench", "Complex, library-heavy code tasks. Where HumanEval saturation ends."),

# ---------------- small_ondevice_models : 5 ----------------
("small_ondevice_models", 1, "Phi-3 Technical Report", "Phone-capable model from curated data. The flagship small-model result."),
("small_ondevice_models", 1, "Gemma 2", "Open small model with distillation and interleaved attention."),
("small_ondevice_models", 2, "TinyLlama", "Fully open small-model training run; heavily over-trained on purpose."),
("small_ondevice_models", 2, "MobileLLM", "Sub-billion architecture design for on-device use."),
("small_ondevice_models", 2, "SmolLM2", "Current open small-model recipe with the full data pipeline published."),
]
